<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="18301" started-at="2021-03-14T04:50:34Z" finished-at="2021-03-14T04:50:53Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="18301" started-at="2021-03-14T04:50:34Z" finished-at="2021-03-14T04:50:53Z">
      <class name="com.jakartalabs.fullstack_automation.APITests">
        <test-method status="PASS" signature="testloginAPIWithIncorrectCredentials()[pri:1, instance:com.jakartalabs.fullstack_automation.APITests@53d1b9b3]" name="testloginAPIWithIncorrectCredentials" duration-ms="15969" started-at="2021-03-14T04:50:35Z" finished-at="2021-03-14T04:50:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testloginAPIWithIncorrectCredentials -->
        <test-method status="FAIL" signature="testloginAPI()[pri:1, instance:com.jakartalabs.fullstack_automation.APITests@53d1b9b3]" name="testloginAPI" duration-ms="16102" started-at="2021-03-14T04:50:35Z" finished-at="2021-03-14T04:50:51Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.jakartalabs.utils.APIActions.verifyAPIResponseDetails(APIActions.java:22)
at com.jakartalabs.fullstack_automation.APITests.testloginAPI(APITests.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testloginAPI -->
        <test-method status="FAIL" signature="testDashboardAPI()[pri:2, instance:com.jakartalabs.fullstack_automation.APITests@53d1b9b3]" name="testDashboardAPI" duration-ms="1933" started-at="2021-03-14T04:50:51Z" finished-at="2021-03-14T04:50:53Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at com.jakartalabs.utils.APIActions.verifyAPIResponseDetails(APIActions.java:20)
at com.jakartalabs.fullstack_automation.APITests.testDashboardAPI(APITests.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDashboardAPI -->
      </class> <!-- com.jakartalabs.fullstack_automation.APITests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
